= entitygen

This is an attempt to re-create some of the functionality of seam-gen;
The Home Function doesn't work at present!

It generates the five artifacts needed for a single-entity JSF list-detail application:

- ${Entity}Home.java
- ${Entity}List.java
- ${Entity}List.xhtml
- ${Entity}View.xhtml # the Detail page
- ${Entity}Edit.xhtml

== Usage

- Build everything: `mvn package`
- Install it somplace handy: `cp entitygen-0.0.1-SNAPSHOT-jar-with-dependencies.jar ~/lib/entitygen-0.0.1-SNAPSHOT.jar`
- Change directory to where your entity exists and is built: `cd ~/workspace/myproject`
- Run: `java -jar ~/lib/entitygen*.jar MyEntity`

== Pre-requisites:
	Apache Maven for building.

== APIs used:

-	darwinsys-ee API for EntityHome
	Another repo of mine; not in Central yet; clone it and do "mvn install" to install in your .m2/repository
-	Apache DeltaSpike Data for EntityList.

== Limitations/TODOs:

- only does one entity at a time
- assumes you have already coded the Java Entity and it's on your classpath
- assumes you did so using Field annotations instead of Accessor annotations
- assumes a single level of inheritance for entities
- assumes you want to use PrimeFaces UI.
- assumes you don't mind having the output stuck in ../entitygenoutput/
- Does not yet handle any relationships
- Does not yet handle Enums
- Whatever else I didn't think of yet.

Code generation is done using Apache Velocity; you can edit the templates.

Some of these limitations will be easier or harder to remove than others. UTSL.
Pull Requests welcome.
